### ISSUE TITLE
trouble in compiling after changing code 

### ISSUE THREAD

**Issue by 02gaurav** [katjahahn/PortEx#10]
i have added dependency on build.sbt as below:
libraryDependencies += "com.github.katjahahn" % "portex_2.10" % "2.0.2"
but as i started to compile the code its giving a error 
[error] a module is not authorized to depend on itself: com.github.katjahahn#portex_2.10;0.13.5

**Comment by katjahahn** [comment]
The error message seems self explanatory to me. Why did you add the dependency in the first place?

**Comment by katjahahn** [comment]
Closing this because it has nothing to do with PortEx.
