### ISSUE TITLE
Yet another sample that causes inf loop in export section loader

### ISSUE THREAD

**Issue by ad1kus** [katjahahn/PortEx#11]
SHA256: `1a3314dabf890e374bb9bfc15a33339e7aab0a092144cf0634f0be551e34cda0`
[Download link](http://www.filedropper.com/sample_33)
Password: infected

**Comment by katjahahn** [comment]
Thank you, I am working on it.

**Comment by katjahahn** [comment]
Ordinal table address pointed outside the file. Fixed by adding a check.

**Comment by ad1kus** [comment]
Thanks! Will you publish this to maven repo?

**Comment by katjahahn** [comment]
I am going to. Having some issues atm.

**Comment by katjahahn** [comment]
Release on Maven Central for 2.0.9 finished. Should be available soon.
