### ISSUE TITLE
JavaDoc 8.0 exits with failure status due to invalid documentation tags

### ISSUE THREAD

**Issue by RomanHargrave** [katjahahn/PortEx#3]
A new feature in JavaDoc 8.0 is `docLint` which, as the name implies, is a linter. As such, it will return a non-zero status unless ***all*** JavaDoc comments use valid syntax.

This causes an issue when packaging PortEx on JDK 8, for instance, there are several uses of `@param` that are non-compliant, which will cause JavaDoc to exit with an, further resulting in SBT aborting the build.

I fixed this by adding the following line to `build.sbt`

```scala
javacOptions in JavaDoc += "-Xdoclint:none"
```

**Comment by katjahahn** [comment]
Thank you for the issue. I will add the line temporarily to build.sbt and fix the comments.
