### ISSUE TITLE
A sample which breaks PortEx

### ISSUE THREAD

**Issue by drorwolmer** [katjahahn/PortEx#5]
This **Malicious** sample breaks PortEx
sha256: 289ce77373ee44e6e6d7744fb57f7be16d83e06d3c4c42a06598b40b15b2dbc1
Download the sample: http://www.filedropper.com/sample_23
Password: *infected!*

**Comment by katjahahn** [comment]
Confirmed bug. I will take care of it. Thank you for the bug report.

**Comment by katjahahn** [comment]
The bug is fixed with commit 5beee5e. The problem was an invalid offset for the ordinal export table. The next PortEx release will contain the fix. PortexAnalyzer.jar already does.

**Comment by drorwolmer** [comment]
Thanks for the fast response, Highly impressed!
