### ISSUE TITLE
Additional Sample which breaks PortEx

### ISSUE THREAD

**Issue by drorwolmer** [katjahahn/PortEx#6]
This **benign** sample breaks PortEx

**sha256:** 44e5184ca90477851fa65c080aea343fdbc01b1e8379eeafb5583aeb83bbd304
**Sample:** http://www.filedropper.com/sample_24
**Password:** infected!

I am happy to do QA for this tool!

**Comment by drorwolmer** [comment]
And here's another **benign** sample

**sha256:** d1255f503b09dab675b657b6b036ba1bab45c2856143ef7aa6ce8352abfea636
**Sample:** http://www.filedropper.com/d1255f503b09dab675b657b6b036ba1bab45c2856143ef7aa6ce8352abfea636

**Comment by katjahahn** [comment]
Confirmed bug. Thank you for the report.

**Comment by katjahahn** [comment]
Issue solved. Next PortEx release will have the bugfix. PortexAnalyzer is updated.
