### ISSUE TITLE
VersionInfo methods not visible

### ISSUE THREAD

**Issue by mpkusnierz** [katjahahn/PortEx#9]
The wiki says that there should be a VersionInfo.parseFromResources static method, but I don't see this on the version I downloaded from here: https://github.com/katjahahn/PortEx/zipball/master (2.0.6).
Similarly, I don;t see a VersionInfo.getVersionStrings method. Either these methods are not visible, or the code in the zip and the code on master/github are out of sync. Am I going mad?

**Comment by mpkusnierz** [comment]
Have you had a chance to look at this issue yet?

**Comment by AnimeshShaw** [comment]
Have a look at the following two links:

https://github.com/katjahahn/PortEx/blob/c2eac0beea8b29a6e01dd275163b7fdcb6883aff/src/main/java/com/github/katjahahn/parser/sections/rsrc/version/VersionInfo.scala#L120

https://github.com/katjahahn/PortEx/blob/c2eac0beea8b29a6e01dd275163b7fdcb6883aff/src/main/java/com/github/katjahahn/parser/sections/rsrc/version/VersionInfo.scala#L50

Is this what you're looking for?

**Comment by mpkusnierz** [comment]
Yes, those are the methods (I am trying to follow this snippet from the documentation https://github.com/katjahahn/PortEx/wiki/Version-Information) but there is no VersionInfo.parseFromResources static method. Or a getVersionStrings instance method. The methods are there in the source-code as you have highlighted. But not they are not visible in the compiled jar file that I downloaded from here: https://github.com/katjahahn/PortEx/zipball/master (2.0.6)

**Comment by AnimeshShaw** [comment]
I recommend you try, compile and rebuild the jar using sbt. You can get the details in the README.

**Comment by katjahahn** [comment]
Sorry for my late reply. That method is not in the current release. You can either compile the code yourself as AnimeshShaw suggested or wait for the next release. I believe it is time for a new release, but won't be before next week. ;)

**Comment by AnimeshShaw** [comment]
@mpkusnierz here's a quick fat jar for you with the latest updates: http://drive.animeshshaw.com/index.php/s/fQflBVTAXnpxwjG

*Note:* It's just a temporary release.

**Comment by mpkusnierz** [comment]
Thanks for posting the snapshot - unfortunately I couldn't access it (due to security policy) - but I will grab the official release when it is available (hoping for next week). In the time being I'll try to build it locally.

**Comment by AnimeshShaw** [comment]
Alright, cool

, btw I have attached the same here again zipped.
